import { renderAsync } from "@resvg/resvg-js";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { rootDir } from "#shared/config/env.ts";
import { FONT_FILES } from "#shared/fonts/font-files.ts";
import { FONT_FAMILY } from "#shared/fonts/font-family.ts";
import { escapeHtml } from "#shared/text/html-escape.ts";


const WRITTEN_TO = "src/shared/fonts/glyph-advances.ts";

const writtenTo = resolve(rootDir, WRITTEN_TO);

const AT = 126;

const CANVAS_WIDTH = 6000;

const CANVAS_HEIGHT = 300;

const BASELINE = 200;

const LEFT_MARGIN = 100;

const OPAQUE_ENOUGH = 16;

const CHANNELS = 4;

const ALPHA = 3;

const NOTHING = 0;

const ONE = 1;

const BETWEEN = "H";

const PLACES = 4;

const ranges: readonly (readonly [string, string])[] = [
  ["A", "Z"],
  ["a", "z"],
  ["А", "Я"],
  ["а", "я"],
  ["0", "9"],
];

const SINGLES = " ёЁ-—·…,.:%()/+'’&";

const glyphs = (): readonly string[] => {
  const spans = ranges.flatMap(([from, to]) =>
    Array.from({ length: to.codePointAt(NOTHING)! - from.codePointAt(NOTHING)! + ONE }, (_u, at) =>
      String.fromCodePoint(from.codePointAt(NOTHING)! + at)
    )
  );

  return [...new Set([...spans, ...SINGLES])];
};

const fonts = {
  fontFiles: [...FONT_FILES],
  loadSystemFonts: false,
  defaultFontFamily: FONT_FAMILY,
};

const inkWidth = async (drawn: string): Promise<number> => {
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="${String(CANVAS_WIDTH)}" ` +
    `height="${String(CANVAS_HEIGHT)}" viewBox="0 0 ${String(CANVAS_WIDTH)} ${String(CANVAS_HEIGHT)}">` +
    `<text x="${String(LEFT_MARGIN)}" y="${String(BASELINE)}" font-family="${FONT_FAMILY}" ` +
    `font-weight="bold" font-size="${String(AT)}" fill="#fff">${escapeHtml(drawn)}</text></svg>`;

  const { pixels, width, height } = await renderAsync(svg, { font: fonts });

  const lit = Array.from({ length: width * height }, (_unused, at) => at).filter(
    (at) => (pixels[at * CHANNELS + ALPHA] ?? NOTHING) >= OPAQUE_ENOUGH
  );
  const columns = lit.map((at) => at % width);

  return columns.length === NOTHING ? NOTHING : Math.max(...columns) - Math.min(...columns) + ONE;
};

const fingerprint = (): string =>
  createHash("sha256")
    .update(FONT_FILES.map((file) => readFileSync(file)).reduce((all, one) => Buffer.concat([all, one])))
    .digest("hex");

const measured = async (): Promise<Readonly<Record<string, number>>> => {
  const pair = await inkWidth(BETWEEN + BETWEEN);
  const table: Record<string, number> = {};

  for (const glyph of glyphs()) {
    const advance = (await inkWidth(BETWEEN + glyph + BETWEEN)) - pair;

    table[glyph] = Number((advance / AT).toFixed(PLACES));
  }

  return table;
};

const asModule = (table: Readonly<Record<string, number>>, stamp: string): string =>
  [
    '// Generated by "node scripts/tools.ts advances" — do not edit by hand.',
    "// FONT_FINGERPRINT is what docs:check holds the shipped faces against.",
    "",
    `export const FONT_FINGERPRINT = "${stamp}";`,
    "",
    "export const ADVANCES: Readonly<Record<string, number>> = {",
    ...Object.entries(table).map(([glyph, em]) => `  ${JSON.stringify(glyph)}: ${String(em)},`),
    "};",
    "",
  ].join("\n");

export const measureAdvances = async (): Promise<void> => {
  const table = await measured();

  writeFileSync(writtenTo, asModule(table, fingerprint()), "utf8");

  console.log(
    `${WRITTEN_TO} — ${String(Object.keys(table).length)} glyphs measured against the shipped bold face`
  );
};
